# Generated by Django 5.2.1 on 2025-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkingcontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='networkingcontact',
            name='contact_role',
        ),
        migrations.AddField(
            model_name='networkingcontact',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='networkingcontact',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
    ]
