# Generated by Django 5.2.1 on 2025-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_networkingcontact_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitercontact',
            name='stage',
            field=models.CharField(choices=[('cv_submitted', 'CV submitted'), ('phone_screen', 'Phone screen'), ('unsuccessful', 'Unsuccessful'), ('video_interview', 'Video interview')], default='cv_submitted', max_length=32),
        ),
    ]
