# Generated by Django 5.2.1 on 2025-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='category',
            field=models.CharField(choices=[('monthly_targets', 'Monthly Targets-1'), ('networking', 'Networking'), ('industry_qs', 'Industry Conversation Qs'), ('jobs_applied', 'Jobs Applied'), ('direct_approach', 'Direct Approach'), ('recruiters', 'Recruiters')], default='jobs_applied', max_length=30),
        ),
    ]
