# Generated by Django 5.2.1 on 2025-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_recruitercontact_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitercontact',
            name='follow_up',
        ),
        migrations.AddField(
            model_name='recruitercontact',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recruitercontact',
            name='agency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruitercontact',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
