# Generated by Django 5.2.1 on 2025-05-26 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_jobapplication_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('jobs_applied', 'Jobs Applied'), ('linkedin_requests', 'LinkedIn Requests'), ('linkedin_connections', 'LinkedIn Connections'), ('conversations', 'Conversations'), ('linkedin_post', 'LinkedIn Post')], max_length=30)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('week_or_month', models.CharField(max_length=20)),
                ('target', models.PositiveIntegerField(default=0)),
                ('actual', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
