# Generated by Django 5.2.1 on 2025-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_recruitercontact_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkingcontact',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkingcontact',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
