# Generated by Django 5.2.1 on 2025-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_networkingcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='position',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='website',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
