# Generated by Django 5.2.1 on 2025-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_networkingcontact_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkingcontact',
            old_name='date',
            new_name='request_sent',
        ),
        migrations.AddField(
            model_name='networkingcontact',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkingcontact',
            name='conversation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
