# Generated by Django 5.2.1 on 2025-05-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_company_jobapplication_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='response',
            field=models.CharField(choices=[('yes', 'Yes'), ('not_yet', 'Not yet')], default='not_yet', max_length=10),
        ),
    ]
