# Generated by Django 5.2.1 on 2025-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_jobapplication_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytarget',
            name='target',
        ),
        migrations.RemoveField(
            model_name='activitytarget',
            name='week_or_month',
        ),
        migrations.AddField(
            model_name='activitytarget',
            name='day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='activitytarget',
            name='goal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitytarget',
            name='week',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitytarget',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activitytarget',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('daily', 'Daily')], max_length=10),
        ),
    ]
