# Generated by Django 5.2.1 on 2025-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyactivitytarget',
            options={},
        ),
        migrations.AlterField(
            model_name='weeklyactivitytarget',
            name='applications_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyactivitytarget',
            name='direct_approach_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyactivitytarget',
            name='linkedin_connections_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyactivitytarget',
            name='linkedin_posts_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weeklyactivitytarget',
            name='networking_contacts_target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
