# Generated by Django 5.2.1 on 2025-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_activitytarget_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytarget',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
