# Generated by Django 5.2.1 on 2025-05-28 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_activitytarget_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyActivityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('activity', models.CharField(choices=[('jobs_applied', 'Jobs applied for'), ('linkedin_requests', 'LinkedIn requests'), ('linkedin_connections', 'LinkedIn connections'), ('conversations', 'Conversations'), ('linkedin_posts', 'LinkedIn posts')], max_length=30)),
                ('target', models.PositiveIntegerField()),
                ('monday', models.PositiveIntegerField(default=0)),
                ('tuesday', models.PositiveIntegerField(default=0)),
                ('wednesday', models.PositiveIntegerField(default=0)),
                ('thursday', models.PositiveIntegerField(default=0)),
                ('friday', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityTarget',
        ),
    ]
