# Generated by Django 5.2.1 on 2025-05-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_directapproach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directapproach',
            name='reached_out',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In Progress')], default='no', max_length=12),
        ),
    ]
