# Generated by Django 5.2.1 on 2025-05-28 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_recruitercontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('phone_screen', 'Phone screen'), ('video_interview', 'Video interview'), ('technical_assessment', 'Technical assessment'), ('one_way_video', 'One-way video interview'), ('face_to_face', 'Face to face interview'), ('final', 'Final interview')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
