# Generated by Django 5.2.1 on 2025-05-28 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('personal_info', 'Personal Info'), ('project', 'Project'), ('shared_teammates_post', 'Shared teammates post'), ('event', 'Event'), ('industry_content', 'Industry content')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
